FROM registry1.dso.mil/ironbank/tpc/tak/tak-server:latest
COPY start.sh /opt/tak/start.sh
LABEL maintainer="george.e.knauss.ctr@army.mil" \
      version="25.02.01" \
      description="TAK server from Iron Bank with custom start script"
ENTRYPOINT ["/bin/bash","/opt/tak/start.sh"]